[package]
name = "safe-mix"
version = "1.0.0"
authors = ["Parity Technologies <admin@parity.io>"]
build = "build.rs"

[build-dependencies]
rustc_version = "0.2"

[features]
default = ["std"]
std = []
nightly = []
strict = []
